hyperskill_project:
  id: 67
  ide_files: https://stepik.org/media/attachments/lesson/215428/additional_files.json
  is_template_based: false
  use_ide: true
update_date: Thu, 01 Jan 1970 00:00:00 UTC
stages:
- id: 360
  step: 5659
  is_completed: false
- id: 361
  step: 5660
  is_completed: false
- id: 362
  step: 5661
  is_completed: false
- id: 363
  step: 5662
  is_completed: false
- id: 364
  step: 5663
  is_completed: false
- id: 365
  step: 5664
  is_completed: false
